### ISSUE TITLE
Add support for Netbox 3.3

### ISSUE THREAD

**Issue by rodewalder** [sjm-steffann/netbox-ddns#29]
Add support for netbox 3.3

**Comment by tsv1991** [comment]
@rodewalder  I use netbox-ddns with 3.3.1 version without any problem. Today I will try to upgrade to 3.3.6

**Comment by tsv1991** [comment]
@rodewalder I upgraded our Netbox from 3.3.1 to 3.3.6, and I can say for sure that netbox-ddns great work.

**Comment by sgofferj** [comment]
I get a crash at startup

```django.core.exceptions.ImproperlyConfigured: Plugin netbox_ddns requires NetBox maximum version 3.2.999.```

**Comment by flyboyjon** [comment]
> I get a crash at startup
> 
> `django.core.exceptions.ImproperlyConfigured: Plugin netbox_ddns requires NetBox maximum version 3.2.999.`

I had exactly the same issue.  What are you putting into /opt/netbox/local_requirements.txt ?

If you put simply **netbox_ddns** it pulls the code from the PyPi repository, which although has the same version 1.2.4 does not appear to contain the fixes needed for 3.3.  Seems to be an issue with the code there not being up to date. If you check __init__.py in the code, it still shows _max_version = '3.2.999'_

I fixed it by explicitly adding this line to local_requirements.txt to pull from Github :
**git+https://github.com/sjm-steffann/netbox-ddns.git**

**Comment by sgofferj** [comment]
Apparently, the linuxserver docker image doesn't include git... *sigh*

**Comment by YWatchman** [comment]
I should bump version for pypi users, forgot that in the workflow. Whoops.

**Comment by YWatchman** [comment]
Resolved in https://github.com/sjm-steffann/netbox-ddns/commit/31c511b3e1e8f4939c1aba424bdc8194eaa1b85a

https://pypi.org/project/netbox-ddns/

**Comment by sgofferj** [comment]
Jep, works now also in the linuxserver.io docker image again.

**Comment by sgofferj** [comment]
@YWatchman For some reason it stopped working again...

The installation process seems to work:
```
Collecting netbox-ddns
  Downloading netbox_ddns-1.2.5-py3-none-any.whl (24 kB)
Collecting dnspython
  Downloading dnspython-2.2.1-py3-none-any.whl (269 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 269.1/269.1 kB 8.0 MB/s eta 0:00:00
Requirement already satisfied: setuptools in /usr/lib/python3.10/site-packages (from netbox-ddns) (65.6.3)
Installing collected packages: dnspython, netbox-ddns
Successfully installed dnspython-2.2.1 netbox-ddns-1.2.5
```

But then later I get:

```
Python version: 3.10.9 (main, Dec 10 2022, 13:54:12) [GCC 11.2.1 20220219]
[ls.io-init] done.
Python main interpreter initialized at 0x7fef87b22b40
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 203184 bytes (198 KB) for 1 cores
*** Operational MODE: single process ***
running "exec:/usr/bin/python3 ./manage.py collectstatic --noinput" (pre app)...
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/django/core/management/__init__.py", line 259, in fetch_command
    app_name = commands[subcommand]
KeyError: 'collectstatic'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/netbox/netbox/./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3.10/site-packages/django/core/management/__init__.py", line 266, in fetch_command
    settings.INSTALLED_APPS
  File "/usr/lib/python3.10/site-packages/django/conf/__init__.py", line 92, in __getattr__
    self._setup(name)
  File "/usr/lib/python3.10/site-packages/django/conf/__init__.py", line 79, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python3.10/site-packages/django/conf/__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/netbox/netbox/netbox/settings.py", line 727, in <module>
    plugin_config.validate(PLUGINS_CONFIG[plugin_name], VERSION)
  File "/app/netbox/netbox/extras/plugins/__init__.py", line 128, in validate
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Plugin netbox_ddns requires NetBox maximum version 3.3.999.
command "/usr/bin/python3 ./manage.py collectstatic --noinput" exited with non-zero code: 1
Thu Jan 12 13:34:20 2023 - FATAL hook failed, destroying instance
SIGINT/SIGTERM received...killing workers...
Traceback (most recent call last):
  File "/app/netbox/netbox/./netbox/wsgi.py", line 7, in <module>
    application = get_wsgi_application()
  File "/usr/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/lib/python3.10/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/usr/lib/python3.10/site-packages/django/conf/__init__.py", line 92, in __getattr__
    self._setup(name)
  File "/usr/lib/python3.10/site-packages/django/conf/__init__.py", line 79, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python3.10/site-packages/django/conf/__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/app/netbox/netbox/./netbox/settings.py", line 727, in <module>
    plugin_config.validate(PLUGINS_CONFIG[plugin_name], VERSION)
  File "/app/netbox/netbox/./extras/plugins/__init__.py", line 128, in validate
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Plugin netbox_ddns requires NetBox maximum version 3.3.999.
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 164)
spawned uWSGI worker 1 (pid: 186, cores: 1)
[uwsgi-daemons] spawning "/usr/bin/python3 ./manage.py rqworker" (uid: 1000 gid: 1000)
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/django/core/management/__init__.py", line 259, in fetch_command
    app_name = commands[subcommand]
KeyError: 'rqworker'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/netbox/netbox/./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3.10/site-packages/django/core/management/__init__.py", line 266, in fetch_command
    settings.INSTALLED_APPS
  File "/usr/lib/python3.10/site-packages/django/conf/__init__.py", line 92, in __getattr__
    self._setup(name)
  File "/usr/lib/python3.10/site-packages/django/conf/__init__.py", line 79, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python3.10/site-packages/django/conf/__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/netbox/netbox/netbox/settings.py", line 727, in <module>
    plugin_config.validate(PLUGINS_CONFIG[plugin_name], VERSION)
  File "/app/netbox/netbox/extras/plugins/__init__.py", line 128, in validate
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Plugin netbox_ddns requires NetBox maximum version 3.3.999.
daemon "/usr/bin/python3 ./manage.py rqworker" (pid: 187) annihilated
```

**Comment by sgofferj** [comment]
I believe, the current netbox version in the LSIO container is 3.4.0

**Comment by ndom91** [comment]
Sorry to derail, but @sgofferj I'm new to using the linuxserver.io docker image, but a veteran netbox user. How the hell do you install plugins to this? Just mount a `local_requirements.txt` into the main dir when building?

**Comment by sgofferj** [comment]
@ndom91 

--> https://docs.linuxserver.io/general/container-customization

/pool1/docker/netbox/custom-cont-init.d/00-install_netbox_plugins
```
pip3 install --no-cache-dir netbox-ddns
pip3 install --no-cache-dir netbox-qrcode
pip3 install --no-cache-dir netbox-topology-views
pip3 install --no-cache-dir nextbox-ui-plugin
```

/pool1/docker/netbox/netbox/local_requirements.txt
```
netbox-ddns
netbox-qrcode
netbox-topology-views
```
